version: '3'

volumes:
  user-mysql:
    driver: local

services:
  mysql:
    image: "mysql:5.7.30"
    volumes:
      - user-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root31234
      MYSQL_DATABASE: example
    command: --disable-partition-engine-check
    ports:
      - "3308:3306"
